name: Build and Deploy

on:
  workflow_dispatch: # add this event to trigger the workflow manually
    inputs:
      environmentName:
        description: 'name of the environment to deploy'
        default: 'dev'
        required: true
        type: string
env:
  environmentName: ${{ vars.environmentName }}
  resourceGroupName: ${{ vars.resourceGroupName }}

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resourceGroupName }}  
          template: ./InfrastructureAsCode/main.bicep
          parameters: environment=${{ inputs.environmentName }}